debug: false
trace: false

logging:
  level:
    '*': ''
    com:
      zaxxer:
        hikari: ${HIKARI_LOGGING_LVL:ERROR}
    org:
      h2: ${H2_LOGGING_LVL:ERROR}
      hibernate: ${HIBERNATE_LOGGING_LVL:ERROR}
      axonframework: ${AXON_LOGGING_LVL:ERROR}
      springframework:
        web:
          socket:
            config:
              WebSocketMessageBrokerStats: ERROR

server:
  port: ${FOFOLA_PORT:8081}
  error:
    path: /error

spring:
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  resources:
    static-locations: classpath:/templates/

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/pages/
    suffix: .html
