debug: false
trace: false

server:
  shutdown: graceful
  port: ${FOFOLA_PORT:8081}
  error:
    path: /error

spring:

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/pages/
    suffix: .html

  resources:
    static-locations: classpath:/templates/

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  lifecycle:
    timeout-per-shutdown-phase: 10s

logging:
  level:
    '*': ''
    com:
      zaxxer:
        hikari: ${HIKARI_LOGGING_LVL:WARN}
    org:
      h2: ${H2_LOGGING_LVL:WARN}
      hibernate: ${HIBERNATE_LOGGING_LVL:WARN}
      axonframework: ${AXON_LOGGING_LVL:WARN}
