version: "2"
services:

  fofola:
    image: "ermak/fofola:latest"
    container_name: fofola
    ports:
      - "8081:8081"
    environment:
      - SOLR_HOST=http://solr:8983/solr
      - KRAMERIUS_HOST=localhost:80
      - KRAMERIUS_USER=krameriusAdmin
      - KRAMERIUS_PSWD=krameriusAdmin
      - FEDORA_HOST=http://fcrepo:8080/fedora
      - FEDORA_USER=fedoraAdmin
      - FEDORA_PSWD=fedoraAdmin
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PSWD=postgres
      - POSTGRES_JDBC_URL=jdbc:postgresql://db:5432/fofola
      - SUGO_HOST=http://localhost:8082
    mem_limit: 2g
    depends_on:
      - db

  db:
    image: "postgres:11.5"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fofola
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
