version: "2"
services:

  fofola:
    image: "ermak/fofola:latest"
    container_name: fofola
    ports:
      - "8081:8081"
    environment:
      - SOLR_HOST=http://solr:8983/solr
      - KRAMERIUS_HOST=localhost:80
      - KRAMERIUS_USER=krameriusAdmin
      - KRAMERIUS_PSWD=krameriusAdmin
      - FEDORA_HOST=http://fcrepo:8080/fedora
      - FEDORA_USER=fedoraAdmin
      - FEDORA_PSWD=fedoraAdmin
    mem_limit: 2g
