debug: false
trace: false

server:
  shutdown: graceful
  port: ${FOFOLA_PORT:8081}
  error:
    path: /error

spring:

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  lifecycle:
    timeout-per-shutdown-phase: 10s

management:
  endpoint:
    info:
      enabled: true
  info:
    build:
      enabled: true
    env:
      enabled: false
    git:
      enabled: true
  health:
    solr:
      enabled: false

logging:
  level:
    '*': ''
    com:
      zaxxer:
        hikari: ${HIKARI_LOGGING_LVL:WARN}
    org:
      h2: ${H2_LOGGING_LVL:WARN}
      hibernate: ${HIBERNATE_LOGGING_LVL:WARN}
